### ISSUE TITLE
Enforce snake_case or PascalCase to represent Classes in ReasonerStdAPI

### ISSUE THREAD

**Issue by kevinxin90** [NCATSTranslator/ReasonerAPI#134]
Biolink use [PascalCase](https://biolink.github.io/biolink-model/docs/Disease.html) to represent all its classes and [snake_case](https://biolink.github.io/biolink-model/docs/correlated_with.html) to represent all the predicates. Seems at the moment, the majority of the KPs/ARAs implementing the ReasonerStdAPI use snake_case to represent both classes and predicates. I would suggest enforcing aligning with BioLink model when representing data using ReasonerStdAPI as much as possible.

**Comment by edeutsch** [comment]
It seems reasonable. But when did class names in BioLink switch from snake_case to PascalCase? I recall from the start of (the pilot phase of) this project, classes in BioLink were snake_case. I think the reason most KPs/ARAs are using snake_case is because we were told to do it that way because that's how BioLink does it.

**Comment by patrickkwang** [comment]
Regardless of history, we should unify the two, and since there are other breaking changes in the works for the Reasoner API, I think it makes sense to switch to PascalCase here. Conveniently, that's also the [recommended format](https://neo4j.com/docs/cypher-manual/current/syntax/naming/#_recommendations) for node labels in Neo4j.

**Comment by dkoslicki** [comment]
>Regardless of history, we should unify the two, and since there are other breaking changes in the works for the Reasoner API, I think it makes sense to switch to PascalCase here

Given that teams have already been using snake case (iirc) for quite a while, why make this code-breaking change simply to make the ReasonerStdAPI stylistically similar to the Biolink model?

Might be good to hear the value-add of this change, as well as survey if teams (@ehinderer, @stevencox, @CaseyTa, @realmarcin,  @mwawer , @mellybelly , @MarkDWilliams etc.) are already using snake_case or PascalCase. 

Given this is such a large, code breaking change, perhaps it would be appropriate to bring this to the steering committee to weigh in on it.

**Comment by edeutsch** [comment]
SRI node normalizer is using snake_case. Is any ARA or KP besides BTE using PascalCase? I agree that such a huge change should be addressed by the steering committee because if we make this change we all need to do this together or else we all need to implement translators to translate different case styles of different endpoints.

**Comment by CaseyTa** [comment]
I'm not sure Biolink Model has a consistent style. I remember someone, maybe Chris Mungall, mentioning there are differences in styling between the yaml and the documentation. For example, it's ```named thing``` (with a space instead of an underscore) in the yaml and ```NamedThing``` in the documentation.

**Comment by patrickkwang** [comment]
#136
