### ISSUE TITLE
Stale externalDocs links

### ISSUE THREAD

**Issue by vdancik** [NCATSTranslator/ReasonerAPI#190]
URLs in externalDocs for tags point to pages that do not exist and GitHub externalDocs URL is outdated.

**Comment by edeutsch** [comment]
```
  url: https://github.com/NCATS-Tangerine/NCATS-ReasonerStdAPI
```
Should we change this to:
```
https://github.com/NCATSTranslator/ReasonerAPI
```
or point to the eventual documentation page?

As for these:
```
      url: http://reasonerhost.ncats.io/overview.html#predicates
      url: http://reasonerhost.ncats.io/overview.html#query
```
these are not valid because they are intended as placeholders for the documentation URLs of the actual implemented endpoints. This yaml is just a template for actual implementations. There are not currently generic documentation for these endpoints, although we could create some.

**Comment by edeutsch** [comment]
okay to close, @vdancik ?
